variables:
  MAVEN_CLI_OPTS: "-s ./maven-settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
  - .m2/repository/
  - target/

stages:
- compile
- package
- analysis
- test
- deploy

compile:
  stage: compile
  image: gitlab.lucimber.io:4567/docker/building_java:openjdk-11-jdk-headless
  script:
  - "mvn $MAVEN_CLI_OPTS compile"

package:
  stage: package
  image: gitlab.lucimber.io:4567/docker/building_java:openjdk-11-jdk-headless
  before_script:
  - "export JAVA_HOME=$(realpath /usr/bin/javadoc | sed 's@bin/javadoc$@@')"
  script:
  - "mvn $MAVEN_CLI_OPTS package -Dmaven.test.skip=true"
  artifacts:
    paths:
    - "target/*.jar"
    expire_in: 2 weeks
    when: on_success

check-style:
  stage: analysis
  image: gitlab.lucimber.io:4567/docker/building_java:openjdk-11-jdk-headless
  dependencies: [ ]
  script:
  - "mvn $MAVEN_CLI_OPTS checkstyle:check"
  allow_failure: true
  artifacts:
    paths:
    - "target/checkstyle-result.xml"
    expire_in: 1 week
    when: on_failure

programming-flaws:
  stage: analysis
  image: gitlab.lucimber.io:4567/docker/building_java:openjdk-11-jdk-headless
  dependencies: [ ]
  script:
  - "mvn $MAVEN_CLI_OPTS pmd:check"
  allow_failure: true
  artifacts:
    paths:
    - "target/pmd.xml"
    expire_in: 1 week
    when: on_failure

duplicated-code:
  stage: analysis
  image: gitlab.lucimber.io:4567/docker/building_java:openjdk-11-jdk-headless
  dependencies: [ ]
  script:
  - "mvn $MAVEN_CLI_OPTS pmd:cpd-check"
  allow_failure: true
  artifacts:
    paths:
    - "target/cpd.xml"
    expire_in: 1 week
    when: on_failure

bug-patterns:
  stage: analysis
  image: gitlab.lucimber.io:4567/docker/building_java:openjdk-11-jdk-headless
  dependencies: [ ]
  script:
  - "mvn $MAVEN_CLI_OPTS spotbugs:check"
  allow_failure: true
  artifacts:
    paths:
    - "target/spotbugsXml.xml"
    expire_in: 1 week
    when: on_failure

unit-tests:
  stage: test
  image: gitlab.lucimber.io:4567/docker/unit-testing_java:openjdk-11-jdk-headless
  dependencies:
  - package
  script:
  - "mvn $MAVEN_CLI_OPTS test"
  - "percentage=$(cat target/site/jacoco/index.html
      | grep -o \"Total[^%]*%\"
      | grep -o \"[0-9.]*%\")
      && echo \"Code coverage (JaCoCo): ${percentage}\""

deploy:artifactory:
  stage: deploy
  only:
  - master
  image: gitlab.lucimber.io:4567/docker/deploy-java:jdk8-headless
  dependencies: [ ]
  script:
  - "mvn $MAVEN_CLI_OPTS -DskipTests -Dcheckstyle.skip deploy"
