# Continuous Integration Pipeline
# 
# This workflow runs on every push and pull request to main branch:
# 1. Builds the project with Gradle
# 2. Runs unit tests with coverage reporting
# 3. Executes integration tests in Docker containers
# 4. Reports coverage to Codecov
#
# Optimized with caching for faster builds

name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Set up Gradle
      uses: actions/setup-gradle@v4
      with:
        cache-disabled: false
        gradle-version: wrapper
    - name: Build and run tests with detailed output
      run: ./gradlew build --console=plain --info --stacktrace
    - name: Generate code coverage report
      run: ./gradlew jacocoTestReport
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./lib/build/reports/jacoco/test/jacocoTestReport.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Run integration tests with Docker caching
      run: ./gradlew integrationTest
      env:
        DOCKER_BUILDKIT: 1
