name: Security

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 6 * * 1'  # Weekly on Monday at 6 AM UTC

permissions:
  contents: read
  security-events: write

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Run dependency vulnerability scan
      uses: gradle/gradle-build-action@v3
      with:
        arguments: dependencyCheckAnalyze --info
    
    - name: Upload dependency check results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: lib/build/reports/dependency-check-report.sarif
        category: dependency-check